Repository omni-srejitk/omniverse, pull requests merged in 2022-11, with the labels that each got.

#2 OMNI-2001-Feat-Dashboard Page Added
  dashboard/.gitignore
  dashboard/index.html
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/public/logo.png
  dashboard/public/logo_icon.png
  dashboard/public/logo_side_black.png
  dashboard/public/logo_vector.svg
  dashboard/public/vite.svg
  dashboard/src/App.css
  dashboard/src/App.jsx
  dashboard/src/assets/logo_vector.svg
  dashboard/src/axios/index.js
  dashboard/src/components/Cards/Card/Card.jsx
  dashboard/src/components/Cards/Stats/StatCard.jsx
  dashboard/src/components/Carousal/Carousal.jsx
  dashboard/src/components/Charts/BarChart/BarChart.jsx
  dashboard/src/components/Charts/Charts.jsx
  dashboard/src/components/Filter/Filter.jsx
  dashboard/src/components/Header/Header.jsx
  dashboard/src/components/Loaders/Spinner/Spinner.jsx
  dashboard/src/components/Select/Select.jsx
  dashboard/src/components/Sidebar/Sidebar.jsx
  dashboard/src/config/RouterConfig.jsx
  dashboard/src/context/FilterContext/FilterCompose.jsx
  dashboard/src/context/FilterContext/FilterContext.jsx
  dashboard/src/context/FilterContext/FilterReducer.js
  dashboard/src/features/data/dataSlice.js
  dashboard/src/index.css
  dashboard/src/main.jsx
  dashboard/src/routes/Analytics/Analytics.jsx
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/routes/Login/Login.jsx
  dashboard/src/routes/Marketing/Marketing.jsx
  dashboard/src/routes/Stores/Stores.jsx
  dashboard/src/services/apiCalls.jsx
  dashboard/src/utils/RequireAuth.jsx
  dashboard/src/utils/constants.js
  dashboard/src/utils/helperFunctions.js
  dashboard/tailwind.config.cjs
  dashboard/vercel.json
Labels: enhancement

#7 Feat : Added Inventory page
  dashboard/src/components/Buttons/Button/Button.jsx
  dashboard/src/components/Buttons/index.js
  dashboard/src/components/Cards/StatsCard/StatCard.jsx
  dashboard/src/components/Carousal/Carousal.jsx
  dashboard/src/components/Select/Select.jsx
  dashboard/src/components/Table/TableBody/TableBody.jsx
  dashboard/src/components/Table/TableContainer/TableContainer.jsx
  dashboard/src/components/Table/TableData/TableData.jsx
  dashboard/src/components/Table/TableFoot/TableFoot.jsx
  dashboard/src/components/Table/TableHead/TableHead.jsx
  dashboard/src/components/Table/TableHeader/TableHeader.jsx
  dashboard/src/components/Table/TableRow/TableRow.jsx
  dashboard/src/components/Table/index.js
  dashboard/src/config/RouterConfig.jsx
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/routes/Inventory/Inventory.jsx
  dashboard/src/services/apiCalls.jsx
  dashboard/src/utils/constants.js
Labels: enhancement

#10 FEAT Map Component Add
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/src/components/Map/Map.jsx
  dashboard/src/components/Map/MapComponent.jsx
  dashboard/src/components/Map/Styles.module.css
  dashboard/src/routes/Stores/Stores.jsx
Labels: enhancement

#11 Feat : Modal Component Added
  dashboard/index.html
  dashboard/src/components/Modal/Modal.jsx
  dashboard/src/components/ModalGallery/ModalGallery.jsx
Labels: enhancement

#12 Feat : Stores Page Added
  dashboard/src/components/Buttons/Button/Button.jsx
  dashboard/src/components/Cards/StatsCard/StatCard.jsx
  dashboard/src/components/Cards/StoreCard/StoreCard.jsx
  dashboard/src/components/Carousal/Carousal.jsx
  dashboard/src/components/Header/Header.jsx
  dashboard/src/components/Labels/TierLabels/TierLabels.jsx
  dashboard/src/components/Labels/index.js
  dashboard/src/components/Map/MapComponent.jsx
  dashboard/src/components/Modal/Modal.jsx
  dashboard/src/components/Modal/StoreModal/StoreModal.jsx
  dashboard/src/components/ModalGallery/ModalGallery.jsx
  dashboard/src/components/Table/TableContainer/TableContainer.jsx
  dashboard/src/components/Table/TableData/TableData.jsx
  dashboard/src/components/Table/TableHead/TableHead.jsx
  dashboard/src/components/Table/TableRow/TableRow.jsx
  dashboard/src/index.css
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/routes/Inventory/Inventory.jsx
  dashboard/src/routes/Login/Login.jsx
  dashboard/src/routes/Stores/Stores.jsx
  dashboard/src/services/apiCalls.jsx
  dashboard/src/utils/constants.js
Labels: enhancement

#15 OMNI-2006-Feat Redux dependency Added
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/src/App.jsx
  dashboard/src/components/Buttons/Button/Button.jsx
  dashboard/src/components/Filter/Filter.jsx
  dashboard/src/components/Header/Header.jsx
  dashboard/src/components/Select/Select.jsx
  dashboard/src/config/RouterConfig.jsx
  dashboard/src/context/FilterContext/FilterCompose.jsx
  dashboard/src/context/FilterContext/FilterContext.jsx
  dashboard/src/context/FilterContext/FilterReducer.js
  dashboard/src/features/data/dataSlice.js
  dashboard/src/main.jsx
  dashboard/src/redux/features/authSlice.js
  dashboard/src/redux/features/dataSlice.js
  dashboard/src/redux/features/filterSlice.js
  dashboard/src/redux/store.js
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/routes/Inventory/Inventory.jsx
  dashboard/src/routes/Login/Login.jsx
  dashboard/src/utils/RequireAuth.jsx
  dashboard/src/utils/helperFunctions.js
Labels: enhancement

#18 OMNI-2009-Refactor code formatting
  dashboard/src/App.jsx
  dashboard/src/components/Cards/StatsCard/StatCard.jsx
  dashboard/src/components/Cards/StoreCard/StoreCard.jsx
  dashboard/src/components/Cards/index.js
  dashboard/src/components/Carousal/Carousal.jsx
  dashboard/src/components/Carousal/index.js
  dashboard/src/components/Charts/AreaChart/AreaChart.jsx
  dashboard/src/components/Charts/index.js
  dashboard/src/components/Filter/Filter.jsx
  dashboard/src/components/Header/Header.jsx
  dashboard/src/components/Labels/index.js
  dashboard/src/components/Loaders/index.js
  dashboard/src/components/Map/MapComponent.jsx
  dashboard/src/components/ModalGallery/ModalGallery.jsx
  dashboard/src/components/Modals/Modal/Modal.jsx
  dashboard/src/components/Modals/StoreModal/StoreModal.jsx
  dashboard/src/components/Modals/index.jsx
  dashboard/src/components/Select/Select.jsx
  dashboard/src/components/index.js
  dashboard/src/redux/actions/authActions.js
  dashboard/src/redux/actions/dataActions.js
  dashboard/src/redux/actions/filterActions.js
  dashboard/src/redux/actions/index.js
  dashboard/src/redux/features/authSlice.js
  dashboard/src/redux/features/dataSlice.js
  dashboard/src/redux/features/filterSlice.js
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/routes/Inventory/Inventory.jsx
  dashboard/src/utils/helperFunctions.js
Labels: enhancement

#22 OMNI-2011-fix update live stores code
  dashboard/src/App.jsx
  dashboard/src/components/Modals/StoreModal/StoreModal.jsx
Labels: bug

#23 Fix : Updated Live Stores API
  dashboard/src/App.jsx
  dashboard/src/components/Modals/StoreModal/StoreModal.jsx
Labels: bug

#26 OMNI-2010-feat stores API integration
  dashboard/src/App.jsx
  dashboard/src/components/Buttons/Button/Button.jsx
  dashboard/src/components/Cards/StoreCard/StoreCard.jsx
  dashboard/src/components/Header/Header.jsx
  dashboard/src/components/Labels/TierLabels/TierLabels.jsx
  dashboard/src/components/Map/MapComponent.jsx
  dashboard/src/components/ModalGallery/ModalGallery.jsx
  dashboard/src/components/Modals/Modal/Modal.jsx
  dashboard/src/components/Modals/StoreModal/StoreModal.jsx
  dashboard/src/redux/features/authSlice.js
  dashboard/src/redux/features/dataSlice.js
  dashboard/src/redux/features/filterSlice.js
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/routes/Inventory/Inventory.jsx
  dashboard/src/routes/Login/Login.jsx
  dashboard/src/routes/Stores/Stores.jsx
  dashboard/src/services/apiCalls.jsx
  dashboard/src/utils/constants.js
  dashboard/src/utils/helperFunctions.js
Labels: feature

#17 added Pie, vertical Bar and Composed Charts
  dashboard/src/components/Charts/BarChart/VerticalBarChart.jsx
  dashboard/src/components/Charts/ComposedChart/ComposedChartComp.jsx
  dashboard/src/components/Charts/PieChart/PieChartComp.jsx
Labels: feature

#25 FEAT - Analytics code done
  dashboard/src/utils/helperFunctions.js
Labels: feature

#32 OMNI-2014-refactor code updates
  dashboard/src/App.jsx
  dashboard/src/components/Carousal/Carousal.jsx
  dashboard/src/routes/Stores/Stores.jsx
  dashboard/src/utils/constants.js
  dashboard/src/utils/helperFunctions.js
Labels: refactor

#33 OMNI-2014-Refactor-Minor-Code-Changes
  dashboard/src/App.jsx
  dashboard/src/components/Carousal/Carousal.jsx
  dashboard/src/routes/Stores/Stores.jsx
  dashboard/src/utils/constants.js
  dashboard/src/utils/helperFunctions.js
Labels: refactor
