Repository omni-srejitk/omniverse, pull requests merged in 2022-12, with the labels that each got.

#39 FEAT Analytics graph done
  dashboard/src/components/Cards/AnalyticsLineGraphCard/AnalyticsChart.jsx
  dashboard/src/components/Cards/index.js
  dashboard/src/components/Charts/LineChart/LineChartComponent.jsx
  dashboard/src/components/Charts/index.js
  dashboard/src/components/index.js
  dashboard/src/utils/helperFunctions.js
Labels: enhancement

#40 OMNI-2017-feat adding analytics page
  dashboard/src/App.jsx
  dashboard/src/components/Buttons/Button/Button.jsx
  dashboard/src/components/Cards/AnalyticsLineGraphCard/AnalyticsChart.jsx
  dashboard/src/components/Cards/Card/Card.jsx
  dashboard/src/components/Charts/Analytics/UnitSold.jsx
  dashboard/src/components/Charts/AreaChart/AreaChart.jsx
  dashboard/src/components/Charts/BarChart/BarChart.jsx
  dashboard/src/components/Charts/BarChart/VerticalBarChart.jsx
  dashboard/src/components/Charts/GenderChart/GenderChart.jsx
  dashboard/src/components/Charts/LineChart/LineChartComponent.jsx
  dashboard/src/components/Charts/PieChart/PieChartComp.jsx
  dashboard/src/components/Filter/Filter.jsx
  dashboard/src/components/Loaders/ProgressBar/ProgressBar.jsx
  dashboard/src/components/PercentageChange/PercentageChange.jsx
  dashboard/src/components/Placeholders/ComingSoon.jsx
  dashboard/src/components/Select/Select.jsx
  dashboard/src/routes/Analytics/Analytics.jsx
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/utils/helperFunctions.js
Labels: feature

#45 OMNI-2018-feat-adding date range selector
  dashboard/src/components/Cards/AnalyticsLineGraphCard/AnalyticsChart.jsx
  dashboard/src/components/DateSelector/DateSelector.jsx
  dashboard/src/components/Filter/Filter.jsx
  dashboard/src/components/Header/Header.jsx
  dashboard/src/components/MonthCalendar/MonthCalendar.jsx
  dashboard/src/components/Select/Select.jsx
  dashboard/src/redux/actions/filterActions.js
  dashboard/src/redux/actions/index.js
  dashboard/src/redux/actions/popupActions.js
  dashboard/src/redux/features/filterSlice.js
  dashboard/src/redux/features/popupSlice.js
  dashboard/src/redux/store.js
  dashboard/src/routes/Analytics/Analytics.jsx
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/utils/constants.js
  dashboard/src/utils/helperFunctions.js
Labels: enhancement

#46 OMNI-2019-refactor stores page live stores update
  dashboard/src/components/Cards/StoreCard/StoreCard.jsx
  dashboard/src/components/Charts/AreaChart/AreaChart.jsx
  dashboard/src/components/Charts/BarChart/BarChart.jsx
  dashboard/src/components/Charts/PieChart/PieChartComp.jsx
  dashboard/src/components/MonthCalendar/MonthCalendar.jsx
  dashboard/src/components/Table/TableContainer/TableContainer.jsx
  dashboard/src/hooks/useCalculateSaleData.jsx
  dashboard/src/hooks/usePrepareData.jsx
  dashboard/src/routes/Analytics/Analytics.jsx
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/routes/Inventory/Inventory.jsx
  dashboard/src/routes/Stores/Stores.jsx
  dashboard/src/utils/constants.js
  dashboard/src/utils/helperFunctions.js
Labels: enhancement

#44 OMNI-2020-Feat-GTM-Added
  dashboard/package.json
  dashboard/src/App.jsx
  dashboard/src/components/Cards/AnalyticsLineGraphCard/AnalyticsChart.jsx
Labels: feature, api integration

#47 Feat : Added Analytics and Store Page
  dashboard/package.json
  dashboard/src/App.jsx
  dashboard/src/components/Buttons/Button/Button.jsx
  dashboard/src/components/Cards/AnalyticsLineGraphCard/AnalyticsChart.jsx
  dashboard/src/components/Cards/Card/Card.jsx
  dashboard/src/components/Cards/StoreCard/StoreCard.jsx
  dashboard/src/components/Cards/index.js
  dashboard/src/components/Carousal/Carousal.jsx
  dashboard/src/components/Charts/Analytics/UnitSold.jsx
  dashboard/src/components/Charts/AreaChart/AreaChart.jsx
  dashboard/src/components/Charts/BarChart/BarChart.jsx
  dashboard/src/components/Charts/BarChart/VerticalBarChart.jsx
  dashboard/src/components/Charts/GenderChart/GenderChart.jsx
  dashboard/src/components/Charts/LineChart/LineChart.jsx
  dashboard/src/components/Charts/LineChart/LineChartComponent.jsx
  dashboard/src/components/Charts/PieChart/PieChartComp.jsx
  dashboard/src/components/Charts/index.js
  dashboard/src/components/DateSelector/DateSelector.jsx
  dashboard/src/components/Filter/Filter.jsx
  dashboard/src/components/Header/Header.jsx
  dashboard/src/components/Loaders/ProgressBar/ProgressBar.jsx
  dashboard/src/components/Loaders/Spinner/Spinner.jsx
  dashboard/src/components/Loaders/index.js
  dashboard/src/components/MonthCalendar/MonthCalendar.jsx
  dashboard/src/components/PercentageChange/PercentageChange.jsx
  dashboard/src/components/Placeholders/ComingSoon.jsx
  dashboard/src/components/Select/Select.jsx
  dashboard/src/components/Sidebar/Sidebar.jsx
  dashboard/src/components/Table/TableContainer/TableContainer.jsx
  dashboard/src/components/index.js
  dashboard/src/hooks/useCalculateSaleData.jsx
  dashboard/src/hooks/usePrepareData.jsx
  dashboard/src/redux/actions/dataActions.js
  dashboard/src/redux/actions/filterActions.js
  dashboard/src/redux/actions/index.js
  dashboard/src/redux/actions/popupActions.js
  dashboard/src/redux/features/dataSlice.js
  dashboard/src/redux/features/filterSlice.js
  dashboard/src/redux/features/popupSlice.js
  dashboard/src/redux/store.js
  dashboard/src/routes/Analytics/Analytics.jsx
  dashboard/src/routes/Dashboard/Dashboard.jsx
  dashboard/src/routes/Inventory/Inventory.jsx
  dashboard/src/routes/Login/Login.jsx
  dashboard/src/routes/Stores/Stores.jsx
  dashboard/src/services/apiCalls.jsx
  dashboard/src/utils/constants.js
  dashboard/src/utils/helperFunctions.js
Labels: enhancement

#55 OMNI-2024-Feat-Added-CSV-Download
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/src/routes/Analytics/Analytics.jsx
Labels: enhancement
